name: tests

on:
  # Run this workflow every time a new commit is pushed to repo
  push:
  # Also run it once weekly to check for impact due to changes in the OS,
  # python, postgres, or any external packages/dependencies
  schedule:
  - cron: '7 14 * * fri'

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # Test with specific supported versions
          - name: supported
            os: ubuntu-18.04
            python: 3.6
            postgres: 9.5
          # Test everything with latest versions
          - name: latest
            os: ubuntu-latest
            python: 3.x
            postgres: latest

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      # Cache entire Python environment
      # - uses: actions/cache@v2
      #   with:
      #     path: ${{ env.pythonLocation }}
      #     # pythonLocation includes exact Python version
      #     key: build-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov
          pip install codecov
      - name: Test with pytest
        run: DB_TEST_URL=postgresql://postgres:postgres@localhost:5432/ pytest --cov-report html --cov pgmerge --verbose
      - name: Get final code coverage percentage & color
        run: |
          COV_TOTAL=$(coverage report | grep 'TOTAL' | tr -s ' ' | cut -d ' ' -f 4)
          COV_COLOR="yellow"
          echo "COV_TOTAL=$COV_TOTAL" >> $GITHUB_ENV
          echo "COV_COLOR=$COV_COLOR" >> $GITHUB_ENV
      - name: Create code coverage badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 3c84321138784d39b31a02d7fe93b31d
          filename: badge-coverage.json
          label: coverage
          message: ${{ env.COV_TOTAL }}
          color: ${{ env.COV_COLOR }}
      - name: Upload coverage to Codecov
        # Ensure we only upload once per build
        if: matrix.name == 'supported'
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
